#! /bin/sh -e

set -e

deb-systemd-helper unmask microphone-server.service >/dev/null || true

if deb-systemd-helper --quiet was-enabled microphone-server.service; then
	deb-systemd-helper enable microphone-server.service >/dev/null || true
else
	deb-systemd-helper update-state microphone-server.service >/dev/null || true
fi

exit 0
